# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-10 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ticker_symbol', models.CharField(max_length=5)),
                ('date_of_IPO', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ticker_symbol', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProffitUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a proffit use (e.g. Buyback or Dividen)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the stock', max_length=1000)),
                ('tickersymbol', models.CharField(help_text='Ticker symbole used to identify publicly traded shares', max_length=5, verbose_name='TickerSymbol')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockcatalog.Company')),
                ('proffituse', models.ManyToManyField(help_text='Select a proffituse for this stock', to='stockcatalog.ProffitUse')),
            ],
        ),
    ]
