# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcatalog', '0003_stock_stockgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockgraph',
            field=models.ImageField(blank=True, upload_to='stock_graphs'),
        ),
    ]
