# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcatalog', '0004_auto_20180411_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stockgraph',
        ),
    ]
